server:
    port: 8080

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/e-commerce
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true